export const proyectos = [
    {
        id: 1,
        nombre: "TO-DO List",
        descripcion: "Una aplicación que nos permite realizar un CRUD completo, Crear una tarea, Leer la tarea, Actualizar nuestra tarea y Eliminarla.",
        stack: "React - JSX - Tailwind - LocalStorage",
        link_preview: "#",
        link_github: "#",
        imagen: "to-do.jpg",    
    },
    {
        id: 2,
        nombre: "Aplicación de Super Héroes",
        descripcion: "Una aplicación que nos permite realizar un CRUD completo, Crear una tarea, Leer la tarea, actualizar nuestra tarea y eliminarla.",
        stack: "React - JSX - Tailwind - LocalStorage",
        link_preview: "#",
        link_github: "#",
        imagen: "heroes.jpg",
    },
    {
        id: 3,
        nombre: "Aplicación del Clima",
        descripcion: "Una aplicación que nos permite realizar un CRUD completo, Crear una tarea, Leer la tarea, actualizar nuestra tarea y eliminarla.",
        stack: "React - JSX - Tailwind - LocalStorage",
        link_preview: "#",
        link_github: "#",
        imagen: "clima.jpg",
    },
    {
        id: 4,
        nombre: "Landing Page Personal",
        descripcion: "Esta aplicación es la carta de presentación, donde se puede visualizar la información de Perfil, Estudios, Experiencia, Portafolio y Contacto",
        stack: "React - JSX - MaterialUI",
        link_preview: "https://landingpagekennier.web.app/",
        link_github: "https://github.com/kennierlujan/LandingPageMUI",
        imagen: "landing.jpg",
    },
];